version: "3.9"

services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DSN=postgres://user:password@postgres:5432/app_db?sslmode=disable
    networks:
      - appnet

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app_db"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  appnet: